# Generated by Django 3.0.5 on 2020-08-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='calorie',
            name='measurement',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
