# Generated by Django 3.0.5 on 2020-08-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200819_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodservoire',
            name='deficient_nutrients',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='foodservoire',
            name='food_complement',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='foodservoire',
            name='major_nutrients',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='foodservoire',
            name='major_nutrients_functions',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
